=== jsalgua027/Lenguaje-Marca/Dtd/Relacion Final/Ejercicio20 y 21/version Profe/motor.dtd
<!--
<!ELEMENT fabrica (piezas, motores, secciones, empleados)>
<!ELEMENT piezas (pieza+)>
<!ELEMENT pieza EMPTY>
<!ATTLIST pieza
	id ID #REQUIRED
	compuesta IDREFS #IMPLIED>
<!ELEMENT motores (motor+)>
<!ELEMENT motore (trabajador+)>
<!ATTLIST motor
	id ID #REQUIRED
	responsable IDREF #REQUIRED
	piezas IDREFS #REQUIRED>
<!ELEMENT trabajador EMPTY>
<!ATTLIST trabajador
	cod ID #REQUIRED
	familiares IDREFS #IMPLIED>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion EMPTY>
<!ATTLIST seccion
	cod ID #REQUIRED
	motores IDREFS #REQUIRED>
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado EMPTY>
<!ATTLIST empleado nif ID #REQUIRED>
-->


<!ELEMENT fabrica (piezas, motores, secciones, empleados)>
<!ELEMENT piezas (pieza+)>
<!ELEMENT pieza EMPTY>
<!ENTITY % id_req "ID #REQUIRED">
<!ENTITY % idrefs_req "IDREFS #REQUIRED">
<!ENTITY % idref_req "IDREF #REQUIRED">
<!ENTITY % idrefs_imp "IDREFS #IMPLIED">

<!ATTLIST pieza
	id %id_req;
	compuesta %idrefs_imp;>
<!ELEMENT motores (motor+)>
<!ELEMENT motor (trabajador+)>
<!ATTLIST motor
	id %id_req;
	responsable %idref_req;
	piezas %idrefs_req;>
<!ELEMENT trabajador EMPTY>
<!ATTLIST trabajador
	cod  %idref_req;
	familiares %idrefs_imp;>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion EMPTY>
<!ATTLIST seccion
	cod %id_req;
	motores %idrefs_req;>
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado EMPTY>
<!ATTLIST empleado nif %id_req;>

=== jsalgua027/Lenguaje-Marca/Dtd/Relacion Final/Ejercicio20 y 21/version Profe/motor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fabrica SYSTEM "motor.dtd">

<fabrica>
	<piezas>
		<pieza id="p1" compuesta="p2 p3"/>
		<pieza id="p2"/>
		<pieza id="p3"/>
		<pieza id="p4"/>
	</piezas>
	<motores>
		<motor id="m1" responsable="_111" piezas="p1 p4">
			<trabajador cod="_111"/>
			<trabajador cod="_222" familiares="_333 _444"/>
		</motor>
		<motor id="m2" responsable="_222" piezas="p3">
			<trabajador cod="_111"/>
			<trabajador cod="_222" familiares="_333"/>
		</motor>
		<motor id="m3" responsable="_444" piezas="p2">
			<trabajador cod="_444"/>
			<trabajador cod="_555" familiares="_666"/>
		</motor>
	</motores>
	<secciones>
		<seccion cod="s1" motores="m1 m2"/>
		<seccion cod="s2" motores="m3"/>
	</secciones>
	<empleados>
		<empleado nif="_111"/>
		<empleado nif="_222"/>
		<empleado nif="_333"/>
		<empleado nif="_444"/>
		<empleado nif="_555"/>
		<empleado nif="_666"/>
	</empleados>
</fabrica>
