=== jsalgua027/Lenguaje-Marca/personas/personas.xsd
<?xml version="1.0" encoding="UTF-8"?>
 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="personas" type="tipoPersonas"/>

    <xs:complexType name="tipoPersonas">
        <xs:sequence>
            <xs:element name="persona" type="tipoPersona" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="tipoPersona">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="nacimiento" type="tipoNacimiento" minOccurs="0"></xs:element>
            <xs:element name="direcciones" type="tipoDirecciones" minOccurs="0"></xs:element>
            
            <xs:choice>
                <xs:element name="hembra" type="tipoSexo"></xs:element>
                <xs:element name="varon" type="tipoSexo"></xs:element>
            </xs:choice>
        </xs:sequence>
        
    </xs:complexType>

    <xs:complexType name="tipoSexo">
                                        <!-- elemento complejo por que es vacio el tipo de sexo puede o no estrar-->
    </xs:complexType>
    <xs:complexType name="tipoNacimiento">
        <xs:attribute name="dia" type="tipoDia"/>
        <xs:attribute name="mes" type="tipoMes"/>
        <xs:attribute name="anyo" type="tipoAnyo"/>
    </xs:complexType>

    <xs:simpleType name="tipoDia">
     <xs:restriction base="xs:positiveInteger">
         <xs:minInclusive value="1"/>
         <xs:maxInclusive value="31"/>
     </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoMes">
     <xs:restriction base="xs:string">
         <xs:pattern value="Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Nomviembre|Diciembre"/>
     </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoAnyo">
     <xs:restriction base="xs:positiveInteger">
        
         <xs:minExclusive value="1900"/>
         <xs:maxInclusive value="2010"/>
     </xs:restriction>
    </xs:simpleType>    

    <xs:complexType name="tipoDirecciones">
        <xs:sequence>
            <xs:element name="direccion" type="tipoDireccion" maxOccurs="unbounded" ></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoDireccion">
        <xs:sequence>
            <xs:element name="calle" type="tipoNombre"></xs:element>
            <xs:element name="poblacion" type="tipoNombre"></xs:element>
            <xs:element name="provincia" type="tipoNombre"></xs:element>
            <xs:element name="cpostal" type="tipoCpostal"></xs:element>
        </xs:sequence>
    </xs:complexType> 


    <xs:simpleType name="tipoNombre">
        <xs:restriction base="xs:string">
          <xs:maxLength value="50"/>
        </xs:restriction>
       </xs:simpleType>    

       
       
       <xs:simpleType name="tipoCpostal">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="10000"/>
            <xs:maxInclusive value="99999"/>
        </xs:restriction>
       </xs:simpleType>    

 
</xs:schema>

=== jsalgua027/Lenguaje-Marca/personas/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personas.xsd">
    <persona>
        <nombre>Juan Pardo</nombre>
        <nacimiento dia="10" mes="Abril" anyo="1982"></nacimiento>
        <direcciones>
            <direccion>
                <calle>caoba,1</calle>
                <poblacion>Madrid</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28055</cpostal>
            </direccion>
        </direcciones>
        <varon/>


    </persona>
    <persona>
        <nombre>Maria Lopez</nombre>
        <nacimiento dia="10" mes="Abril" anyo="1982"></nacimiento>
        <direcciones>
            <direccion>
                <calle>Roncato,1</calle>
                <poblacion>Illescas</poblacion>
                <provincia>toledo</provincia>
                <cpostal>42500</cpostal>
            </direccion>
            <direccion>
                <calle>Paseo de la esperanza, 5</calle>
                <poblacion>Madrid</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28005</cpostal>
            </direccion>
        </direcciones>
        <varon></varon>


    </persona>
</personas>
