=== jsalgua027/Lenguaje-Marca/NachoSalcedoExamenJunio/examen_rec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bib" type="tipoBiblioteca"/>
    
    <xs:complexType name="tipoBiblioteca">
        <xs:sequence>
            <xs:element name="libro" type="tipoLibro" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoLibro">
        <xs:sequence>
            <xs:element name="titulo" type="tipoTexto"/>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="autor" type="tipoAutor" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element name="editor" type="tipoEditor"/>
                </xs:sequence>
            </xs:choice>
            <xs:element name="editorial" type="tipoTexto"/>
            <xs:element name="precio" type="tipoPrecio"/>
        </xs:sequence>
        <xs:attribute name="año" type="xs:string" use="required"/>
        <xs:attribute name="moneda" type="tipoMoneda" use="required"/>
    </xs:complexType>

    <xs:simpleType name="tipoMoneda">
        <xs:restriction base="xs:string">
            <xs:pattern value="(euro|dólar)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipoAutor">
        <xs:sequence>
            <xs:element name="apellido" type="tipoTexto" minOccurs="1"/>
            <xs:element name="nombre" type="tipoTexto" minOccurs="1"/>
            <xs:element name="nacido" type="tipoNacido" minOccurs="0"/>
        </xs:sequence>
       
    </xs:complexType>

    <xs:complexType name="tipoNacido" mixed="true">
            <xs:attribute name="mes" type="tipoMes" use="required"/>
        
    </xs:complexType>

    <xs:simpleType name="tipoMes">
        <xs:restriction base="xs:string"> 
            <xs:pattern value="(enero|febrero|marzo|abril|mayo|junio|agosto|septiembre|octubre|nomviembre|diciembre)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipoEditor">
        <xs:sequence>
            <xs:element name="apellido" type="tipoTexto" minOccurs="1"/>
            <xs:element name="nombre" type="tipoTexto" minOccurs="1"/>
            <xs:element name="nacido" type="tipoNacido" minOccurs="0"/>
            <xs:element name="afiliacion" type="xs:string" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tipoPrecio">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxExclusive value="1000"/>
            <xs:totalDigits value="5"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTexto">
        <xs:restriction base="xs:string">
         <xs:minLength value="2"/>
         <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== jsalgua027/Lenguaje-Marca/NachoSalcedoExamenJunio/examen_rec.xml
<?xml version="1.0" encoding="UTF-8"?>
<bib xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="examen_rec.xsd">
    <libro año="1994" moneda="euro">
        <titulo>TCP/IP Illustrated</titulo>
        <autor>
            <apellido>Stevens</apellido>
            <nombre>W.</nombre>
        </autor>
        
        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
    </libro>
    <libro año="1992" moneda="euro">
        <titulo>Advan Programming for Unix environment</titulo>
        <autor>
            <apellido>Stevens</apellido>
            <nombre>W.</nombre>
        </autor>
        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
    </libro>
    <libro año="2000" moneda="dólar">
        <titulo>Data on the Web</titulo>
        <autor>
            <apellido>Abiteboul</apellido>
            <nombre>Serge</nombre>
            <nacido mes="febrero">1975</nacido>
        </autor>
        <autor>
            <apellido>Buneman</apellido>
            <nombre>Peter</nombre>
        </autor>
        <autor>
            <apellido>Suciu</apellido>
            <nombre>Dan</nombre>
        </autor>
        <editorial>Morgan Kaufmann editorials</editorial>
        <precio>39.95</precio>
    </libro>
    <libro año="1999" moneda="euro">
        <titulo>Economics of Technology for Digital TV</titulo>
        <editor>
            <apellido>Gerbarg</apellido>
            <nombre>Darcy</nombre>
            <nacido mes="marzo">1966</nacido>
            <afiliacion>CITI</afiliacion>
        </editor>
        <editorial>Kluwer Academic editorials</editorial>
        <precio>129.95</precio>
    </libro>
</bib>
