=== jsalgua027/Lenguaje-Marca/Dtd/Relacion Final/Ejercicio 18 y 19/libreta.dtd
<!ELEMENT libreta (usuarios* , clientes*)>
<!ELEMENT usuarios (usuario*)>
<!ATTLIST usuario id ID #REQUIRED>
<!ELEMENT usuario (nombre+, telefono+, direccion+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono EMPTY>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT clientes (cliente*)>
<!ATTLIST cliente id ID #REQUIRED>
<!ELEMENT cliente (nombre+, telefono+, direccion+)>

=== jsalgua027/Lenguaje-Marca/Dtd/Relacion Final/Ejercicio 18 y 19/Libreta_de_direcciones.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE libreta SYSTEM "libreta.dtd">


<libreta>
	<usuarios>
		<usuario id="_01">
			<nombre>pepe</nombre>
			<telefono/>
			<direccion>calle del cielo</direccion>
		</usuario>
	</usuarios>
	<clientes>
		<cliente id="_02">
			<nombre>juan </nombre>
			<telefono/>
			<direccion>calle del mar</direccion>
		</cliente>
	</clientes>
</libreta>
