=== jsalgua027/Lenguaje-Marca/UltimoExamen/Empresa/empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa" type="tipoEmpresa"/>
    <xs:complexType name="tipoEmpresa">
        <xs:sequence>
            <xs:element name="datos_empresa" type="tipoDatosEmpresa"/>
            <xs:element name="clientes" type="tipoClientes"/>
            <xs:element name="factura" type="tipoFactura" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

<xs:complexType name="tipoDatosEmpresa">
        <xs:sequence>
          <xs:group ref="datosGrupo"></xs:group>
            <xs:element name="cif" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="telefono" type="xs:positiveInteger" fixed="917776688" use="required"/>
        <xs:attribute name="fax" type="xs:positiveInteger" fixed="917776699" use="required"/>
    </xs:complexType>
    
 <xs:complexType name="tipoPoblacion" mixed="true">
    <xs:attribute name="cod_postal" type="xs:positiveInteger"/>

 </xs:complexType>
 <xs:complexType name="tipoClientes">
     <xs:sequence>
         <xs:element name="cliente" type="tipoCliente" maxOccurs="unbounded"/>
     </xs:sequence>
 </xs:complexType>

 <xs:complexType name="tipoCliente">
    <xs:sequence>
        <xs:group ref="datosGrupo"></xs:group>
        <xs:element name="telefono" type="tipoTelefono" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="n_cli" type="xs:ID" use="required"/>
 </xs:complexType>
<xs:complexType name="tipoTelefono">
    <xs:attribute name="num" type="xs:positiveInteger"/>
</xs:complexType>


<xs:group name="datosGrupo">
    <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:choice>
            <xs:element name="dir" type="xs:string"/>
            <xs:element name="dir_env" type="xs:string"/>
        </xs:choice>
        <xs:element name="poblacion" type="tipoPoblacion"/>
        <xs:element name="provincia" type="xs:string"/>
       
    </xs:sequence>
</xs:group>

<xs:complexType name="tipoFactura">
    <xs:sequence>
        <xs:element name="datos_factura" type="tipoDatosFactura"/>
    </xs:sequence>
    <xs:attribute name="n_fac" type="xs:ID" use="required"/>
    <xs:attribute name="cli" type="xs:IDREF" use="required"/>

</xs:complexType>

<xs:complexType name="tipoDatosFactura">
    <xs:sequence>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="linea" type="tipoLinea" maxOccurs="unbounded"/>
        <xs:element name="base" type="xs:decimal" minOccurs="0"/>
        <xs:element name="cuota_iva" type="xs:decimal"/>
        <xs:element name="total" type="xs:decimal"/>
    </xs:sequence>
    <xs:attribute name="n_ped" type="xs:ID" use="required" />
    <xs:attribute name="iva" type="xs:string" />
    <xs:attribute name="f_pago" type="tipoPago" />
    <xs:attribute name="moneda" type="xs:string" fixed="euro" use="required" />
</xs:complexType>

<xs:complexType name="tipoLinea">
    <xs:sequence>
        <xs:element name="ref" type="xs:string"/>
        <xs:element name="desc" type="xs:string" />
        <xs:element name="cant" type="xs:positiveInteger"/>
        <xs:element name="precio" type="xs:decimal"/>
        <xs:element name="importe" type="xs:decimal"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="tipoPago">
    <xs:restriction base="xs:string">
        <xs:pattern value="efectivo|tarjeta|plazos"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== jsalgua027/Lenguaje-Marca/UltimoExamen/Empresa/empresa.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="empresa.xsd">
    <datos_empresa telefono="917776688" fax="917776699">
        <nombre>Equipos Digitales S.L.</nombre>
        <dir>Av. Valladolid</dir>
        <poblacion cod_postal="28043">Madrid</poblacion>
        <provincia>Madrid</provincia>
        <cif>Q-9876543</cif>
    </datos_empresa>
    <clientes>
        <cliente n_cli="c1">
            <nombre>Darío, Bueno Gutiérrez</nombre>
            <dir_env>Av. Oporto nº7 4ºd</dir_env>
            <poblacion cod_postal="28043">Madrid</poblacion>
            <provincia>Madrid</provincia>
            <telefono num="600655388"/>
        </cliente>
        <cliente n_cli="c2">
            <nombre>Juan, Lara Ortega</nombre>
            <dir_env>Av. España nº17 6ºc</dir_env>
            <poblacion cod_postal="29680">Estepona</poblacion>
            <provincia>Málaga</provincia>
        </cliente>
    </clientes>
    <factura n_fac="f1" cli="c1">
        <datos_factura n_ped="p1" iva="16" f_pago="tarjeta" moneda="euro">
            <fecha>2016-01-05</fecha>
            <linea>
                <ref>MII93000F/8</ref>
                <desc>MICRO PENTIUM IV 3000MHZ FB800</desc>
                <cant>1</cant>
                <precio>230</precio>
                <importe>266.80</importe>
            </linea>
            <linea>
                <ref>MB8QDIP4</ref>
                <desc>PLACA BASE QDI P4</desc>
                <cant>1</cant>
                <precio>180</precio>
                <importe>208.80</importe>
            </linea>
            <linea>
                <ref>MEDD512M32</ref>
                <desc>DIMM DDR 512MB 3200</desc>
                <cant>2</cant>
                <precio>40</precio>
                <importe>92.80</importe>
            </linea>
            <linea>
                <ref>HD250GSA7</ref>
                <desc>DISCO DURO 250GB S-ATA 7200</desc>
                <cant>4</cant>
                <precio>120</precio>
                <importe>556.80</importe>
            </linea>
            <base>970.00</base>
            <cuota_iva>155.20</cuota_iva>
            <total>1125.20</total>
        </datos_factura>
    </factura>
    <factura n_fac="f2" cli="c2">
        <datos_factura n_ped="p4" iva="16" f_pago="efectivo" moneda="euro">
            <fecha>2016-01-17</fecha>
            <linea>
                <ref>MII93000F/8</ref>
                <desc>MICRO PENTIUM IV 3000MHZ FB800</desc>
                <cant>2</cant>
                <precio>230</precio>
                <importe>266.80</importe>
            </linea>
            <base>460.00</base>
            <cuota_iva>73.60</cuota_iva>
            <total>533.60</total>
        </datos_factura>
    </factura>
</empresa>
